name: confichat
description: "Lightweight, multi-platform, and privacy focused LLM chat interface with optional encryption"
publish_to: 'none'
version: 0.1.0

msix_config:
  display_name: ConfiChat
  publisher: CN=3D1F3D3D-3D3D-3D3D-3D3D-3D3D3D3D3D3D
  publisher_display_name: Beyond Reality Labs Limited
  identity_name: ai.confichat.windows
  msix_version: 0.7.1.0
  capabilities: internetClient, location

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  desktop_drop: ^0.5.0
  desktop_window: ^0.4.0
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  http: ^1.2.2
  intl: ^0.20.2
  markdown: ^7.2.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  path: ^1.8.3
  pdfrx: ^1.0.82
  encrypt: ^5.0.3
  crypto: ^3.0.3
  code_highlight_view: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/confichat_logo.png
    - assets/confichat_logo_text_outline.png
    - assets/TERMS_AND_CONDITIONS.md
    - assets/licenses/
