name: confichat
description: "Lightweight, multi-platform, and privacy focused LLM chat interface with optional encryption"
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  yaml: ^3.1.2
  desktop_drop: ^0.5.0
  desktop_window: ^0.4.0
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  http: ^1.2.2
  intl: any
  markdown: ^7.2.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  path: ^1.8.3
  pdfrx: ^1.0.82
  encrypt: ^5.0.3
  crypto: ^3.0.3
  code_highlight_view: ^0.1.1
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/confichat_logo.png
    - assets/confichat_logo_text_outline.png
    - assets/TERMS_AND_CONDITIONS.md
    - assets/licenses/
    - assets/i18n/languages.yaml
    - assets/i18n/en.json
    - assets/i18n/ar.json
    - assets/i18n/de.json
    - assets/i18n/es.json
    - assets/i18n/fil.json
    - assets/i18n/fr.json
    - assets/i18n/he.json
    - assets/i18n/it.json
    - assets/i18n/th.json
    - assets/i18n/zh.json