name: confichat
description: "Lightweight, multi-platform, and privacy focused LLM chat interface with optional encryption"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  desktop_drop: ^0.4.4
  desktop_window: ^0.4.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.3+1
  http: ^1.2.2
  intl: ^0.19.0
  markdown: ^7.2.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  path: ^1.8.3
  pdfrx: ^1.0.82
  encrypt: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_oss_licenses: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/confichat_logo.png
    - assets/confichat_logo_text_outline.png
    - assets/TERMS_AND_CONDITIONS.md
    - assets/licenses/
