name: iOS

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      release_name:
        required: true
        type: string

  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**.md'
      - '.github/**'
      - 'docs/**'

  pull_request:
    branches:
      - main

      
jobs:
  ios-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.1.7
    
    - name: Set up Java
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: 'stable'

    - name: Install dependencies
      run: cd confichat && flutter pub get

    - name: Update third party licenses iOS
      run: cd confichat && flutter pub run flutter_oss_licenses:generate.dart

    - name: Build iOS App
      run: cd confichat && flutter build ios --release  --no-codesign 

#    - name: Sign iOS App
#      run: |
#        cd confichat/build/ios/iphoneos
#        xcodebuild -workspace confichat.xcworkspace -scheme confichat -archivePath confichat.xcarchive archive
#       xcodebuild -exportArchive -archivePath confichat.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath .
#        codesign --verify --verbose confichat.ipa
