name: macOS Test Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main

jobs:
  macos-test-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable

      - name: Install dependencies
        run: cd confichat && flutter pub get

      - name: Update third party licenses macOS
        run: cd confichat && flutter pub run flutter_oss_licenses:generate.dart

      - name: Configure macOS build
        run: cd confichat && flutter build macos --release --config-only

      - name: Compile unsigned macOS test build
        run: |
          cd confichat/macos
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release \
            -destination 'generic/platform=macOS' CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER= CODE_SIGN_IDENTITY= build -quiet
